### ISSUE TITLE
Remove the necessity to include all binaries in the docker image

### ISSUE THREAD

**Issue by fredclausen** [sdr-enthusiasts/acars_router#68]
Ideally during the build phase we test and include only the appropriate binary for the architecture, if for no other reason than to save some space on the download. I am thinking the best way to accomplish this would be:

* Copy all binaries in as well do now
* Run a script that emulates the startup checks done presently, and if one passes remove the other binaries and rename the good one to `acars_router`

**Comment by mikenye** [comment]
Resolved via #71
